// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package di

import (
	"github.com/intrsokx/Go-000/Week04/config"
	"github.com/intrsokx/Go-000/Week04/internal/dao"
	"github.com/intrsokx/Go-000/Week04/internal/service"
	"github.com/intrsokx/Go-000/Week04/pkg/email"
)

// Injectors from wire.go:

//di 依赖注入
//声明依赖注入文件
func NewService() (*service.Service, error) {
	emailCfg := config.NewEmailCfg()
	emailEmail := email.NewEmail(emailCfg)
	dbCfg := config.NewDbCfg()
	userRepo := dao.NewUserRepo(dbCfg)
	serviceService := service.NewService(emailEmail, userRepo)
	return serviceService, nil
}
